# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'mute' -Path (Join-Path (Join-Path $toolsDir 'bin') 'mute.bat')
Install-BinFile -Name 'volume' -Path (Join-Path (Join-Path $toolsDir 'bin') 'volume.bat')
